In [88]:
import numpy as np

In [89]:
my_list=[1,2,3,4,5]

In [90]:
type(my_list)

list

In [91]:
my_array=np.array(my_list)

In [92]:
type(my_array)

numpy.ndarray

In [94]:
print(my_array)

[1 2 3 4 5]


In [96]:
my_array.shape #one dimensional array.

(5,)

In [100]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[3,4,5,6,7]

my_array1=np.array([my_list1,my_list2,my_list3])

In [101]:
type(my_array1)

numpy.ndarray

In [103]:
print(my_array1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [108]:
my_array1.shape # 3 rows, 5 column

(3, 5)

In [105]:
my_array1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [106]:
my_array1.reshape(1,15) # we can only convert the array here into an array with 15 elements

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

In [113]:
print(my_array1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [117]:
my_array1[1:2,1:4] # <included>:<excluded>

array([[3, 4, 5]])

In [118]:
my_array=np.array([1,2,3,4,5,6,7,8,9])

In [119]:
my_array[3:]=100 # Copy function or Broadcasting

In [120]:
my_array

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [124]:
arr=np.array([1,2,3,4,5,6])

In [125]:
arr1=arr

In [126]:
arr1[3:]=100

In [128]:
arr1

array([  1,   2,   3, 100, 100, 100])

In [129]:
arr  # array is a Reference Type and shares the same memory space. Any update on any variable reflects to all other places

array([  1,   2,   3, 100, 100, 100])

In [130]:
lst=[1,2,3,4,5,6]

In [131]:
lst1=lst

In [134]:
lst1[3]=100

In [135]:
lst1

[1, 2, 3, 100, 5, 6]

In [136]:
lst

[1, 2, 3, 100, 5, 6]

In [137]:
arr2=arr.copy() # To prevent the negative impact of Reference Type. copy() function does not share the same memory space.

In [138]:
arr2[3:]=300

In [139]:
arr2

array([  1,   2,   3, 300, 300, 300])

In [140]:
arr

array([  1,   2,   3, 100, 100, 100])

In [141]:
np.ones(4) #to create an array of all elements as 1. By default the datatype is float

array([1., 1., 1., 1.])

In [142]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [145]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [144]:
np.random.rand(3,3) # a random distribution between 0 to 1. will change with every execution

array([[0.03415662, 0.59460086, 0.4329031 ],
       [0.06709338, 0.60587869, 0.42200953],
       [0.18240305, 0.90698492, 0.52192041]])

In [146]:
np.random.randn(4,4) # a random distribution between 0 and 1 but in a standard normal distribution format

array([[-1.0180968 , -0.56696132, -1.43825623,  1.88860846],
       [-1.14775264, -0.52484493, -0.57051155,  0.57354028],
       [ 1.1600258 ,  0.77792768,  1.04630694, -0.20994328],
       [-1.79284569, -1.57367064,  2.58785886, -1.22795233]])

In [147]:
np.random.randint(0,100,8) # rand 8 numbers between 0 to 100

array([10, 10, 82,  6, 50, 25,  9, 55])

In [148]:
np.random.randint(0,100,8).reshape(2,4)

array([[45, 16,  4, 81],
       [66, 85, 24, 35]])