In [1]:
import numpy as np

## The Basics

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# Get Dimensions
b.ndim

2

In [14]:
# Get the shape
b.shape

(2, 3)

In [17]:
# Get datatype
a.dtype

dtype('int32')

In [23]:
a = np.array([1,2,3], dtype='int32')
a.dtype

dtype('int32')

In [24]:
# Get Size
a.itemsize # int16 will have 2 bytes.. and int32 will have 4 bytes

4

In [25]:
# Get total size
a.size*a.itemsize 

# a.nbytes

12

### Accessing/Changing specific elements, rows, columns etc

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [27]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# Get specific element [row_index, column_index]
a[1,5]

13

In [29]:
# Using reverse indexing
a[1,-2]

13

In [30]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
a[:,0]

array([1, 8])

In [35]:
# [start_index:end_index:step_size]
#a[0,1:6:2]

# Using reverse index
a[0,1:-1:2]

array([2, 4, 6])

In [36]:
# Update a particular cell

a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [38]:
# Update all rows of a particular column

a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [39]:
# Update all rows of a particular column with different values

a[:,2] = [30,40]
print(a)

[[ 1  2 30  4  5  6  7]
 [ 8  9 40 11 12 20 14]]


#### 3D Array

In [40]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
b.ndim

3

In [42]:
b.shape

(2, 2, 2)

In [43]:
b.itemsize

4

In [44]:
b.nbytes

32

In [45]:
b[0,1,1]

4

In [46]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [47]:
b[:,0,0]

array([1, 5])

In [48]:
b[:,0,:] = [[9,9],[8,8]]
print(b)

[[[9 9]
  [3 4]]

 [[8 8]
  [7 8]]]


#### Initializing Different Types of Arrays

In [51]:
# All 0s

np.zeros((2,3,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [55]:
# All 1s

np.ones((4,5,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [56]:
# Any other number

np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [59]:
# using the shaping of other array

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

#np.full_like(a,4)

np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [60]:
# Random values

np.random.rand(4,2)

array([[0.24309763, 0.60723638],
       [0.14247504, 0.4905979 ],
       [0.05926802, 0.85000111],
       [0.9613621 , 0.62330846]])

In [61]:
np.random.rand(4,2,3)

array([[[0.97285495, 0.09843369, 0.14564681],
        [0.2730448 , 0.60557203, 0.89446451]],

       [[0.93566326, 0.49781916, 0.67692039],
        [0.76889174, 0.75562603, 0.94986675]],

       [[0.57685534, 0.93716313, 0.17618083],
        [0.19742386, 0.72435052, 0.50710234]],

       [[0.10160861, 0.65656062, 0.98026088],
        [0.61212355, 0.61547089, 0.45733568]]])

In [63]:
np.random.random_sample(a.shape)

array([[0.43825003, 0.98503211, 0.40163174, 0.1926999 , 0.40763495,
        0.39100592, 0.17120226],
       [0.3154964 , 0.2417143 , 0.76288233, 0.39591118, 0.55760565,
        0.05576891, 0.23506906]])

In [64]:
# Random integers

np.random.randint(7)

3

In [67]:
np.random.randint(7, size = (3,3))

array([[4, 6, 6],
       [4, 0, 3],
       [2, 3, 5]])

In [77]:
np.random.randint(4,7, size = (3,3))

array([[5, 4, 4],
       [4, 5, 4],
       [5, 4, 5]])

In [79]:
# identity matrix

np.identity(5, dtype = 'int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [83]:
# Repeat elements

arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [84]:
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [85]:
r1 = np.repeat(arr,3,axis=1)
print(r1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [86]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [87]:
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [88]:
c = np.zeros((5,5), dtype='int32')
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [89]:
c[2,2]=9
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 9 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [91]:
c[0,:]=1
c[:,0]=1
c[-1,:]=1
c[:,-1]=1
print(c)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [93]:
# Alternate

c=np.ones((5,5), dtype='int32')
z=np.zeros((3,3),  dtype='int32')
z[1,1]=9
c[1:-1,1:-1]=z
print(c)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Copying from one array to another

In [95]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [96]:
b = a
b

array([1, 2, 3])

In [97]:
# Make change in b
b[0] = 100
b

array([100,   2,   3])

In [98]:
a

array([100,   2,   3])

In [101]:
# numpy interprets b=a as b being point to same memory as a
# any change in b or a will reflect in the other
# to avoid this we use .copy()

a = np.array([1,2,3])
b = a.copy()
b[0] = 100

In [102]:
b

array([100,   2,   3])

In [103]:
a

array([1, 2, 3])

#### Mathematics

In [104]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [105]:
a+2

array([3, 4, 5, 6])

In [106]:
a-2

array([-1,  0,  1,  2])

In [107]:
a*2

array([2, 4, 6, 8])

In [108]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [109]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [110]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [111]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [113]:
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

##### Linear Algebra

In [114]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [115]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [116]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [117]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [118]:
# Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [119]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
np.min(stats)

1

In [121]:
np.max(stats)

6

In [123]:
np.min(stats, axis=1)

array([1, 4])

In [125]:
np.max(stats, axis=0)

array([4, 5, 6])

In [126]:
np.sum(stats)

21

In [127]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [128]:
np.sum(stats, axis=1)

array([ 6, 15])

##### Reorganizing Arrays

In [129]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [131]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [132]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [133]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [136]:
# Vetrical Stacking

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [137]:
np.vstack([v1,v2,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [139]:
# Horizontal Stacking

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
v1 = np.zeros((2,4))
v2 = np.ones((2,2))

np.hstack([v1,v2])

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])